# site settings
title: Forty
subtitle: by HTML5 UP
email: contactmaroofsha@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/forty" # the subpath of your site, e.g. /blog
url: "https://maroofsha.gitlab.io/forty" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://maroofsha.gitlab.io/maroofsha
googleplus_url: https://plus.google.com/
instagram_url: https://instagram.com/maroofshasoaps
linkedin_url: https://www.linkedin.com/
pinterest_url: https://pinterest.com/maroofsha2012
slack_url:
twitter_url: https://twitter.com/maroofsha2012

# build settings
markdown: kramdown

sass:
  style: compressed
